### DISCUSSION TITLE
Creation of Docker Compose File & Fixed firstrun and firstsync

### DISCUSSION THREAD

**Discussion by austinsonger** [Secure-Compliance-Solutions-LLC/GVM-Docker#190] [General]
- Fix firstrun and firstsync #179
> Added `/data/` to `firstrun` and `firstsync`

**Result**
```
/data/firstrun
/data/firstsync
```

- Create docker-compose file #186
```
version: "3"
services:
    gvm:
        image: securecompliance/gvm
        volumes:
          - <path to data>:/data
        environment:
          - USERNAME="admin"
          - PASSWORD="admin"
          - RELAYHOST="smtp"
          - SMTPPORT=25
          - AUTO_SYNC=true
          - HTTPS=true
          - TZ="UTC"
          - SSHD=false
          - DB_PASSWORD="none"
        ports:
          - "8080:9392"  # Web interface
          #- "5432:5432" # Access PostgreSQL database from external tools
          #- "2222:22"   # SSH for remote sensors
        restart: unless-stopped
```

If you test this new release and run into any issues please add your comments to this release discussion and please make sure to include the following information

**Host Device:**

- OS:
- Version:

<hr /><em>This discussion was created from the release <a href='https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/releases/tag/21.4.0-v4'>Creation of Docker Compose File & Fixed firstrun and firstsync</a>.</em>
